# Generated by Django 5.0.7 on 2024-07-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacuationcenter',
            name='location',
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.barangay'),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
        migrations.AlterField(
            model_name='affectedarea',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.barangay'),
        ),
    ]
