# Generated by Django 4.2 on 2026-03-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_familydistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="is_pregnant_lactating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="familymember",
            name="is_pwd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="familymember",
            name="sector",
            field=models.CharField(
                blank=True,
                help_text="e.g. Senior Citizen, Children, Out-of-School Youth, Solo Parent, Indigenous Peoples, Farmers/Fisherfolk",
                max_length=50,
                null=True,
            ),
        ),
    ]
