# Generated by Django 4.2.23 on 2026-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_familymember_is_pregnant_lactating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='house_condition',
            field=models.CharField(choices=[('Not Damaged', 'Not Damaged'), ('Partially Damaged', 'Partially Damaged'), ('Totally Damaged', 'Totally Damaged')], default='Not Damaged', max_length=20),
        ),
    ]
